### PR TITLE
Add pound.cfg file and TimeOut and RewriteLocation directives in cfg

### PR DESCRIPTION
**Pull request by sorinsugar**
### Description
I've moved the pound.cfg file to this repo and added the following directives as configurable variables: TimeOut and RewriteLocation.
These are added as ENV variables inside the docker files (to provide default values) and the values can be controlled from docker-compose if needed. 

### Fixed Issues (if relevant)
1. Magento timeout if the request TTFB takes more than 15 seconds (default value for pound proxy)
2. Pound proxy rewrites location by default to the request URL so it breaks redirects to outside websites (eg external SSO)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento-cloud-docker?pullRequest=37) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento-cloud-docker?pullRequest=37) before we can accept your contribution.<br/>

**Comment by shiftedreality** [comment]
@sorinsugar thank you for your submission! We are review and process it.

**Comment by shiftedreality** [comment]
@sorinsugar could you please merge latest changes and resolve conflict? We're about to pick it up for QA

**Comment by sorinsugar** [comment]
@shiftedreality I've merged the latest master into my PR.

**Comment by andriyShevtsov** [comment]
Created internal task https://magento2.atlassian.net/browse/MAGECLOUD-4095

**Comment by andriyShevtsov** [comment]
QA approved

**Pull request merged**
