### PR TITLE
MCLOUD-6173: Remove rsyslog from Cloud Docker

### PR DESCRIPTION
**Pull request by shiftedreality**
### Description

Magento Cloud Docker does not use rsyslog and in the latest versions, it throws warnings.
This error should be eliminated by removing rsyslog completely

### Fixed Issues (if relevant)

1. https://jira.corp.magento.com/browse/MCLOUD-6173

### Manual testing scenarios

1. Build PHP images locally
2. Deploy Magento in Production mode
3. Verify there are no warnings during `./bin/magento-docker bash`

### Release notes

* Removed rsyslog from PHP containers to resolve compatibility issues that generated warning notifications during deployment. Magento Cloud Docker does not use the rsyslog utility.

### Associated documentation updates

Updated release notes: https://github.com/magento/devdocs/pull/7356

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Review by bbatsche — APPROVED** [review]

**Review by oshmyheliuk — APPROVED** [review]

**Comment by meker12** [comment]
@shiftedreality For release note, why did you remove rsyslog?

**Comment by shiftedreality** [comment]
We can say `Removed due to compatibility issues`, we actually never used and advertised it as part of the tool

**Comment by meker12** [comment]
> We can say `Removed due to compatibility issues`, we actually never used and advertised it as part of the tool

I updated the release note text above. Take a look and change as needed. Thx.

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by andriyShevtsov** [comment]
Please check tests @shiftedreality

**Comment by shiftedreality** [comment]
The task to fix failing job on 1.1 branch: https://jira.corp.magento.com/browse/MCLOUD-6199

**Pull request merged**
