### PR TITLE
MCLOUD-5981: Added GNUPG extension

### PR DESCRIPTION
**Pull request by G-Arvind**
### Description

Added GNUPG extension to PHP images.
### Fixed Issues (if relevant)

https://jira.corp.magento.com/browse/MCLOUD-5981
1. magento/magento-cloud-docker#177: How to Install and Configure Gnupg 

### Manual testing scenarios

1. Run `php -m | grep "gnupg"`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Review by bbatsche — DISMISSED** [review]

**Review by michaelcasey316 — DISMISSED** [review]

**Comment by andriyShevtsov** [comment]
Failed during building php-fpm 7.3 image locally:
```
Removing intermediate container 9ab0b500cd98
 ---> 76629ca16d54
Step 20/38 : RUN docker-php-ext-enable   bcmath   bz2   calendar   exif   gd   geoip   gettext   gmp   gnupg   igbinary   imagick   imap   intl   ldap   mailparse   msgpack   mysqli   oauth   opcache   pcov   pdo_mysql   propro   pspell   raphf   recode   redis   shmop   soap   sockets   sodium   sysvmsg   sysvsem   sysvshm   tidy   xdebug   xmlrpc   xsl   yaml   zip   pcntl   ioncube
 ---> Running in 0587fdd6c72d
The command '/bin/sh -c docker-php-ext-enable   bcmath   bz2   calendar   exif   gd   geoip   gettext   gmp   gnupg   igbinary   imagick   imap   intl   ldap   mailparse   msgpack   mysqli   oauth   opcache   pcov   pdo_mysql   propro   pspell   raphf   recode   redis   shmop   soap   sockets   sodium   sysvmsg   sysvsem   sysvshm   tidy   xdebug   xmlrpc   xsl   yaml   zip   pcntl   ioncube' returned a non-zero code: 137
```

**Comment by andriyShevtsov** [comment]
@G-Arvind please take a look

**Comment by G-Arvind** [comment]
> @G-Arvind please take a look

Hi @andriyShevtsov , the image got built successfully in my local. 

The error code **137** which you are facing means an out of memory error. So there are chances that the build got failed due to out of memory.

Can you please try this:

`docker inspect <container ID>`

Review the application's memory requirements and ensure that the container it's running in has sufficient memory. 
Thanks.

**Comment by andriyShevtsov** [comment]
Got it. Thank you. I will check

**Comment by andriyShevtsov** [comment]
Also you have a merging conflict with mainline. May you please resolve it

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by shiftedreality** [comment]
@G-Arvind please solve the conflicts

**Comment by G-Arvind** [comment]
Hi @shiftedreality, @bbatsche, @michaelcasey316, @andriyShevtsov fixed the conflicts by removing PHP 7.1 images.

Thanks.

**Review by bbatsche — APPROVED** [review]

**Review by michaelcasey316 — APPROVED** [review]

**Pull request merged**
