### PR TITLE
MCLOUD-6394: Help with running MFTF test generation commands

### PR DESCRIPTION
**Pull request by oshmyheliuk**
### Fixed Issues (if relevant)

https://jira.corp.magento.com/browse/MCLOUD-6394

### Manual testing scenarios

1. Run build:compose command with `--with-selenium` option
2. Check that `docker-compose.yaml` doesn't contain `test` container
3. Run build:compose command with `--with-selenium --with-test` options
4. Check that `docker-compose.yaml`contains `selenium` and `test` containers

### Documentation
https://github.com/magento/devdocs/pull/7995

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Review by bbatsche — APPROVED** [review]

**Review by NadiyaS — APPROVED** [review]

**Comment by andriyShevtsov** [comment]
QA approved

@oshmyheliuk please update documentation https://devdocs.magento.com/cloud/docker/docker-test-app-mftf.html

**Review by BaDos — APPROVED** [review]

**Comment by NadiyaS** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@NadiyaS, an error occurred during the Pull Request import.

**Comment by NadiyaS** [comment]
@magento import pr to magento-cloud/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@NadiyaS, an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-cloud/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@mmansoor-magento, an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-cloud/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@mmansoor-magento, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-cloud/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@sidolov, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@NadiyaS the reason why PR is not imported - the absence of `develop` branch in the target repo. Tool will create the the PR with the same base branch as an original PR. Please, create `develop` branch in your fork and try again to import PR. Let me know if it will not work for you.

**Comment by NadiyaS** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@NadiyaS, an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@mmansoor-magento, an error occurred during the Pull Request import.

**Comment by mmansoor-magento** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@mmansoor-magento, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@sidolov, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-cloud/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@sidolov, an error occurred during the Pull Request import.

**Comment by sidolov** [comment]
@magento import pr to magento-cloud/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@sidolov the pull request successfully imported.

**Comment by NadiyaS** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@NadiyaS the pull request successfully imported.

**Comment by oshmyheliuk** [comment]
Merged into magento-commerce

**Pull request closed without merging**
