### PR TITLE
MAGECLOUD-3978: [Spike][Cloud Docker] DB data should persist in a volume

### PR DESCRIPTION
**Pull request by oshmyheliuk**
### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-3978

### Manual testing scenarios

1. Install magento on docker, check that site works
2. Run `docker-compose down`
3. Run `docker-compose up -d`
4. Connect to mysql from db container and check that database exists
5. Check that Magento frontend is opening.
6. Check in production and developer modes.

https://jira.corp.magento.com/browse/MAGECLOUD-70

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by joeshelton-wagento** [comment]
Pros:

- Increase DB data persistence and prevent unintentional loss of data from the use of the "down" command. Instead users will need to use "docker volume rm" command to dispose of data, which is much more explicit.
- The volume has better namespacing. Frequent users of Docker have many volumes, and a volume named with random characters is difficult to manage.
- Named volume for DB is used by most of the Magento community Docker configurations. User switching to Magento's solution should not find that their usual workflows lead to data loss.
https://github.com/meanbee/docker-magento2
https://github.com/markshust/docker-magento

**Review by ngreimel-lt — APPROVED** [review]
I love it! LGTM

NIT: Could `.docker/mysql/docker-entrypoint-initdb.d` be mounted `ro`?

**Comment by mattskr** [comment]
As mentioned in the closed PR usually we use `docker-compose stop` to shut down the containers and leave our DB intact. We use `docker-compose down` to destroy/recreate.

This works fine for my developers workflow so I think all we need here is better documentation between down and stop.

**Review by mattskr — APPROVED** [review]

**Review by shiftedreality — APPROVED** [review]

**Comment by shiftedreality** [comment]
Thanks for the review! Moved to QA

**Comment by andriyShevtsov** [comment]
QA approved

**Pull request merged**
