### PR TITLE
Add mounts object in Magento cloud application

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
### Description

1.  Added 'mounts' object in the 'MAGENTO_CLOUD_APPLICATION'. Which is missed. 
2.  This PR reverts the temporary fix introduced in magento/ece-tools#781

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#292: The application environment variable does not contain mounts.

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by chiranjeevi-cj** [comment]
@shiftedreality Can you please verify this PR. Thanks!

**Comment by NadiyaS** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@NadiyaS the pull request successfully imported.

**Review by shiftedreality — APPROVED** [review]

**Review by oshmyheliuk — APPROVED** [review]

**Comment by oshmyheliuk** [comment]
@chiranjeevi-cj Thank you for your contribution. Your changes were already released in `1.2.2`.
We accidentally did a squash merge of your pr after importing it to the internal repository. Sorry about this.
https://github.com/magento/magento-cloud-docker/commit/5e33685101fa6fadf77205723cb49d570af52f38

**Pull request closed without merging**
