### PR TITLE
Enhance expect exception tests

### PR DESCRIPTION
**Pull request by peter279k**
### Description
# Changed log
- To support future `PHPUnit 8.x` versions about deprecated `@expectedException` warning message, using the `expectException` and `expectExceptionMessage` instead.
- Removing unused `@throws` annotation.
- Upgrading the PHPUnit `7.x` version and it requires `php-7.1` version at least.

The deprecated warning message is as follows:

```
 with data set "empty string" ('')
The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageRegExp() instead.
```

The related issue is available [here](https://github.com/sebastianbergmann/phpunit/issues/3332).

### Manual testing scenarios
- Travis CI build will be passed.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by shiftedreality** [comment]
Hello @peter279k 

Thank you for your contribution! I've created internal task https://magento2.atlassian.net/browse/MAGECLOUD-4556 to process and merge your PR

**Review by shiftedreality — APPROVED** [review]

**Comment by shiftedreality** [comment]
@peter279k PR overall looks good!

Please merge 1.0 branch and fix a conflict, so I can proceed with merging.

**Comment by peter279k** [comment]
> @peter279k PR overall looks good!
> 
> Please merge 1.0 branch and fix a conflict, so I can proceed with merging.

Hi @shiftedreality, thanks for your reply.

Now I've resolved `composer.json` conflict from the `1.0` branch.

**Comment by shiftedreality** [comment]
Thanks a lot for your contribution!

**Pull request merged**
