### PR TITLE
Add usage of www user

### PR DESCRIPTION
**Pull request by shiftedreality**
### Description

This PR changes ownership of all files in Docker containers to `www:www`:

1. Added new `manual-native` option

This option is inspired by https://github.com/markshust/docker-magento

### Important

This PR has BiC and must be delivered as minor increase of MCD version

### Usage:

1. Generate compose file

```
./bin/ece-docker build:compose --sync-engine manual-native --mode developer
```

2. Upload files into the container:

```
./bin/magento-docker copy-to --all
```

3. Continue with build/deploy
4. Download files from the container if needed:

```
./bin/magento-docker copy-from --all
```

### Fixed Issues (if relevant)

1. https://github.com/magento/magento-cloud-docker/issues/303
2. Removed outdated images (Magento < 2.3)
3. Removed health check from FPM image to not depend on web container

### Manual testing scenarios

1. Build images locally:

```bash
docker build -t test/php:7.4-cli ../magento-cloud-docker/images/php/7.4-cli \
    && docker build -t test/php:7.4-fpm ../magento-cloud-docker/images/php/7.4-fpm
```

2. Add override `docker-compose.override.yml` file:

```
version: '2.1'
services:
  build:
    image: 'test/php:7.4-cli'
  deploy:
    image: 'test/php:7.4-cli'
  fpm:
    image: 'test/php:7.4-fpm'
```

3. Spin up the environment:

```
docker-compose up -d
```

4. Copy files to the container:

```
./bin/magento-docker copy-to --all
```

5. Build & deploy Magento

```
docker-compose run --rm build cloud-build
docker-compose run --rm deploy cloud-deploy
```

6. Open Magento on the frontend

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Docker release notes](https://devdocs.magento.com/cloud/release-notes/mcd-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful release notes and documentation
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by damienwebdev** [comment]
I think that this PR (as it stands) totally misses the mark.

IMHO the BiC is unnecessary and a mistake. 

Instead of forcing Linux/WSL2 users down a more convoluted path that they don't even need, why not just publish a "develop" docker container that runs with the correct permissions (1000:1000) and then provide separate sync strategies for Mac users?

Additionally, the final intent of this PR is unclear.

Are you:


1. Trying to fix Mac Performance? (It seems like you're trying to do this. The manual sync is one of the core reasons for why @markshust does a similar thing in his environment?)
2. Trying to make the app run as a different guid:uid? (The PR seems to target this, but I'd argue that the method is a mistake)

If you want to provide a different `sync` strategy for mac, go ahead, but I don't think it should be blended into this PR.

**Comment by damienwebdev** [comment]
After a discussion in Slack w/ @shiftedreality I think that something like:

```bash
groupadd -g ${GID} www
usermod -g ${GID} www
deluser www
adduser --uid ${UID} --disabled-login --system --gid ${GID} www 
kill -USR2 1 (pid of the master php-fpm process)
```

In an entry point script inside a "development" version of the container would make much more sense. In this way, we can ensure that the php-fpm user is the same as the mounting user's uid/gid.

This would eliminate the conflicts developers see during local development, while allowing for different production time behavior.

Additionally, this should use the sane default of `uid=1000;gid=1000` in the event that UID/GID can't be determined as the 1000:1000 works for most users in 99% of cases unless their development devices are specially provisioned by corporate standards.

**Comment by shiftedreality** [comment]
@magento import pr to magento-commerce/magento-cloud-docker

**Comment by magento-engcom-team** [comment]
@shiftedreality the pull request successfully imported.

**Comment by shiftedreality** [comment]
This PR will be split into 2 different PRs

**Pull request closed without merging**
