### PR TITLE
MAGECLOUD-2886: [Cloud Docker] Add Redis 3.2 and 4.0

### PR DESCRIPTION
**Pull request by oshmyheliuk**
https://magento2.atlassian.net/browse/MAGECLOUD-2886

### CODE REVIEW

**Comment by bbatsche** [comment]
Why are we adding this to our own repository? This is verbatim what is already defined in the official Redis images. All we are doing here is creating more work for ourselves.

https://github.com/docker-library/redis/blob/53348c1c52c3d2e8666fbf748bc9e2297c35b452/3.2/Dockerfile
https://github.com/docker-library/redis/blob/53348c1c52c3d2e8666fbf748bc9e2297c35b452/4.0/Dockerfile

**Comment by shiftedreality** [comment]
@oshmyheliuk could you please check if this works well out-of-the-box?

**Comment by oshmyheliuk** [comment]
@bbatsche yes you are right, I don't really know why we need redis in Magento repository.
Let's remove the whole Redis section.
I made changes in Docker Builder to use Redis image from docker library.
https://github.com/magento/ece-tools/pull/376

**Comment by oshmyheliuk** [comment]
@shiftedreality I've tested this and docker works fine for me with Redis from docker library.

**Pull request merged**
