### PR TITLE
MCLOUD-5586: Upgrade Node.js in the PHP container

### PR DESCRIPTION
**Pull request by mohanelamurugan**
[**MCLOUD-5586**](https://jira.corp.magento.com/browse/MCLOUD-5586): Upgrade Node.js in the PHP container

### Description

Magneto Cloud Docker includes a Node.js installation as part of the CLI containers. This can be seen here: https://github.com/magento/magento-cloud-docker/blob/develop/images/php/cli/Dockerfile#L15

However, the problem is that it installs Node.js 8, which no longer receives security updates according to https://nodejs.org/en/about/releases/

So I have updated the Node.js version to 10

### Fixed Issues (if relevant)

1. magento/magento-cloud-docker#172: Upgrade Node.js in the PHP container

### Manual testing scenarios

1. Run docker-compose run deploy node -v from your project folder.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Review by BaDos — DISMISSED** [review]

**Review by michaelcasey316 — CHANGES_REQUESTED** [review]
This also needs to be changed in magento-cloud-docker/images/php/cli/Dockerfile

**Comment by BaDos** [comment]
@michaelcasey316 thanks! I did not notice it.
@mohanelamurugan edit `images/php/cli/Dockerfile` - this is general template for PHP images
then run the command `bin/ece-docker image:generate:php` - this command add needed changes to all PHP images

**Comment by mohanelamurugan** [comment]
> This also needs to be changed in magento-cloud-docker/images/php/cli/Dockerfile

I have changed that as well. Can you please review it once again ?

**Review by BaDos — APPROVED** [review]

**Review by michaelcasey316 — APPROVED** [review]

**Comment by mveeramneni** [comment]
QA Approved

**Pull request merged**
