### PR TITLE
35 fix tls proxy

### PR DESCRIPTION
**Pull request by aepod**
### Description
Updated timeout values for containers.

### Fixed Issues (if relevant)
1. This PR includes proper formatting for varnish timeouts.

### CODE REVIEW

**Comment by YPyltiai** [comment]
@aepod , is this one a duplicate for https://github.com/magento/magento-cloud-docker/pull/78 ?

**Comment by aepod** [comment]
No one is for 4.x and the other 6.x varnish versions.

**Comment by YPyltiai** [comment]
@shiftedreality, please review.

**Comment by shiftedreality** [comment]
It looks to me like it just has different targets. We will backport all `1.0` changes into `develop` later. Please re-open if closed by mistake.

Closed.

**Comment by aepod** [comment]
6356447 should be merged too, this affects the older varnish config.

**Comment by aepod** [comment]
@YPyltiai Why did you remove the Partner tags? I should be able to get credit for this change.

**Comment by YPyltiai** [comment]
@aepod , we have tags on #78. Based on what @shiftedreality says  these are same changes looks like but to different branch. In most cases if there is same PR into two branches we merge one and then branches are synced. If we miss something, please ping Oleh on Slack to discuss what exactly we missed.

**Pull request closed without merging**
